import { readFile, rm } from "node:fs/promises";
import path from "node:path";
import { runCommand } from "../../utils/ChildProcess.js";
import { findFilesByPredicate } from "../../utils/FileSearch.js";
import { normalizeGithubRepository } from "../../utils/GithubRepository.js";
import { parsePositiveInteger } from "../../utils/PositiveInteger.js";
import { DirtyWatersInstaller } from "./DirtyWatersInstaller.js";
import { DirtyWatersOutputParser } from "./DirtyWatersOutputParser.js";
import { PackageManagerPreflight } from "./PackageManagerPreflight.js";
import { DEFAULT_PACKAGE_MANAGER } from "../../domain/PackageManager.js";

/** Static Dirty-Waters checks required by the prototype smell subset. */
const STATIC_CHECK_FLAGS = [
  "--check-source-code",
  "--check-source-code-sha",
  "--check-deprecated",
  "--check-forks",
  "--check-provenance",
  "--check-code-signature",
  "--check-aliased-packages"
];

/** Default maximum duration for one Dirty-Waters execution. */
const DEFAULT_TIMEOUT_MS = 30 * 60 * 1000;

/** Detector adapter that invokes Dirty-Waters and converts its output to internal findings. */
export class DirtyWatersAdapter {
  /** Configures installer, parser, failure behavior, and command timeout. */
  constructor({
    installer = new DirtyWatersInstaller(),
    parser = new DirtyWatersOutputParser(),
    packageManagerPreflight = new PackageManagerPreflight(),
    commandRunner = runCommand,
    required = false,
    timeoutMs = readTimeoutFromEnvironment()
  } = {}) {
    this.name = "DirtyWatersAdapter";
    this.required = required;
    this.installer = installer;
    this.parser = parser;
    this.packageManagerPreflight = packageManagerPreflight;
    this.commandRunner = commandRunner;
    this.timeoutMs = timeoutMs;
  }

  /** Runs Dirty-Waters for a GitHub project and parses generated static analysis artefacts. */
  async detect(context) {
    const repository = normalizeGithubRepository(context.project.repository);

    if (!repository) {
      return {
        findings: [],
        warnings: ["Dirty-Waters was skipped because no GitHub repository path owner/repo was available."]
      };
    }

    const githubToken = context.githubToken || process.env.GITHUB_API_TOKEN;
    if (!githubToken) {
      throw new Error("Dirty-Waters requires GITHUB_API_TOKEN to access GitHub repository metadata.");
    }

    const baseEnv = {
      ...process.env,
      GITHUB_API_TOKEN: githubToken
    };
    const workingDirectory = context.workspaceDirectory || process.cwd();
    const packageManager = context.project.packageManager || DEFAULT_PACKAGE_MANAGER;
    const env = await this.packageManagerPreflight.prepareEnvironment({
      packageManager,
      env: baseEnv,
      cwd: workingDirectory
    });
    const executable = await this.installer.ensureInstalled({ env, cwd: workingDirectory });
    const startedAt = Date.now();
    const resultRoot = path.join(workingDirectory, "results");
    const args = [
      "-p",
      repository,
      "-pm",
      packageManager,
      "--gradual-report=false",
      ...STATIC_CHECK_FLAGS
    ];

    if (context.project.analysedRef) {
      args.push("-v", context.project.analysedRef);
    }

    let adapterResult = null;

    try {
      const result = await this.commandRunner(executable, args, {
        cwd: workingDirectory,
        env,
        timeoutMs: this.timeoutMs
      });

      if (result.exitCode !== 0) {
        throw new Error(formatDirtyWatersFailure(result, packageManager));
      }

      const staticResultsPath = await this.#findStaticResultsPath(resultRoot, startedAt);
      if (!staticResultsPath) {
        adapterResult = {
          findings: [],
          warnings: ["Dirty-Waters completed but no current *_static_results.json file was found."]
        };
        return adapterResult;
      }

      const staticResults = JSON.parse(await readFile(staticResultsPath, "utf8"));
      const findings = this.parser.parseStaticResults(staticResults, {
        rootDependencyTypesByName: context.graph?.rootDependencyTypesByName ?? {}
      });
      const packageMetadata = this.parser.parsePackageMetadata(staticResults);

      adapterResult = {
        findings,
        warnings: [],
        packageMetadata
      };
      return adapterResult;
    } finally {
      const cleanupWarning = await removeDirtyWatersResults(resultRoot);
      if (cleanupWarning && adapterResult) {
        adapterResult.warnings.push(cleanupWarning);
      }
    }
  }

  /** Locates the Dirty-Waters static result generated by the current run. */
  async #findStaticResultsPath(resultRoot, startedAt) {
    const resultFiles = await findFilesByPredicate(
      resultRoot,
      (_fullPath, fileName) => fileName.endsWith("_static_results.json")
    );
    return newestSince(resultFiles, startedAt)?.path ?? null;
  }
}

/** Removes transient Dirty-Waters reports without allowing cleanup failure to discard findings. */
async function removeDirtyWatersResults(resultRoot) {
  try {
    await rm(resultRoot, {
      recursive: true,
      force: true,
      maxRetries: 5,
      retryDelay: 200
    });
    return null;
  } catch (error) {
    return `Dirty-Waters result cleanup failed: ${error.message}`;
  }
}

/** Selects the newest generated artefact whose modification time matches the current run. */
function newestSince(files, timestampMs) {
  return files.find((file) => file.mtimeMs >= timestampMs - 1000) ?? null;
}

/** Reads an optional Dirty-Waters timeout override from the process environment. */
function readTimeoutFromEnvironment() {
  return parsePositiveInteger(process.env.DIRTY_WATERS_TIMEOUT_MS, DEFAULT_TIMEOUT_MS);
}

/** Builds a concise failure message and highlights common dependency extraction failures. */
function formatDirtyWatersFailure(result, packageManager) {
  const output = `${result.stderr || ""}\n${result.stdout || ""}`.trim();
  const dependencyExtractionHint =
    output.includes("extract_deps_from_npm") || output.includes("WinError 2")
      ? ` Dirty-Waters could not extract ${packageManager} dependencies; verify the required package-manager command is installed and reachable from PATH.`
      : "";

  return `Dirty-Waters failed with exit code ${result.exitCode}.${dependencyExtractionHint}\n${output}`;
}
