import { readFile } from "node:fs/promises";
import path from "node:path";
import { runCommand } from "../../utils/ChildProcess.js";
import { findFilesByPredicate } from "../../utils/FileSearch.js";
import { normalizeGithubRepository } from "../../utils/GithubRepository.js";
import { DirtyWatersInstaller } from "./DirtyWatersInstaller.js";
import { DirtyWatersOutputParser } from "./DirtyWatersOutputParser.js";
import { PackageManagerPreflight } from "./PackageManagerPreflight.js";
import { DEFAULT_PACKAGE_MANAGER } from "../../domain/PackageManager.js";

/** Static Dirty-Waters checks required by the prototype smell subset. */
const STATIC_CHECK_FLAGS = [
  "--check-source-code",
  "--check-source-code-sha",
  "--check-deprecated",
  "--check-forks",
  "--check-provenance",
  "--check-code-signature",
  "--check-aliased-packages"
];

/** Default maximum duration for one Dirty-Waters execution. */
const DEFAULT_TIMEOUT_MS = 30 * 60 * 1000;

/** Detector adapter that invokes Dirty-Waters and converts its output to internal findings. */
export class DirtyWatersAdapter {
  /** Configures installer, parser, failure behavior, and command timeout. */
  constructor({
    installer = new DirtyWatersInstaller(),
    parser = new DirtyWatersOutputParser(),
    packageManagerPreflight = new PackageManagerPreflight(),
    commandRunner = runCommand,
    required = false,
    timeoutMs = readTimeoutFromEnvironment()
  } = {}) {
    this.name = "DirtyWatersAdapter";
    this.required = required;
    this.installer = installer;
    this.parser = parser;
    this.packageManagerPreflight = packageManagerPreflight;
    this.commandRunner = commandRunner;
    this.timeoutMs = timeoutMs;
  }

  /** Runs Dirty-Waters for a GitHub project and parses generated static analysis artefacts. */
  async detect(context) {
    const repository = normalizeGithubRepository(
      context.project.repository || context.githubRepository || process.env.GITHUB_REPOSITORY_PATH
    );

    if (!repository) {
      return {
        findings: [],
        warnings: ["Dirty-Waters was skipped because no GitHub repository path owner/repo was available."]
      };
    }

    const githubToken = context.githubToken || process.env.GITHUB_API_TOKEN;
    if (!githubToken) {
      throw new Error("Dirty-Waters requires GITHUB_API_TOKEN to access GitHub repository metadata.");
    }

    const baseEnv = {
      ...process.env,
      GITHUB_API_TOKEN: githubToken
    };
    const workingDirectory = context.workspaceDirectory || process.cwd();
    const packageManager = context.project.packageManager || DEFAULT_PACKAGE_MANAGER;
    const env = await this.packageManagerPreflight.prepareEnvironment({
      packageManager,
      env: baseEnv,
      cwd: workingDirectory
    });
    const executable = await this.installer.ensureInstalled({ env, cwd: workingDirectory });
    const startedAt = Date.now();
    const args = [
      "-p",
      repository,
      "-pm",
      packageManager,
      "--gradual-report=false",
      ...STATIC_CHECK_FLAGS
    ];

    if (context.project.analysedRef) {
      args.push("-v", context.project.analysedRef);
    }

    const result = await this.commandRunner(executable, args, {
      cwd: workingDirectory,
      env,
      timeoutMs: this.timeoutMs
    });

    if (result.exitCode !== 0) {
      throw new Error(formatDirtyWatersFailure(result, packageManager));
    }

    const artifacts = await this.#findArtifacts(workingDirectory, startedAt);
    if (!artifacts.staticResultsPath) {
      return {
        findings: [],
        warnings: ["Dirty-Waters completed but no *_static_results.json file was found."]
      };
    }

    const staticResults = JSON.parse(await readFile(artifacts.staticResultsPath, "utf8"));
    const findings = this.parser.parseStaticResults(staticResults, {
      rawResultPath: artifacts.staticResultsPath,
      markdownReportPath: artifacts.markdownReportPath
    });

    return {
      findings,
      warnings: [],
      artifacts
    };
  }

  /** Locates the latest Dirty-Waters JSON and Markdown artefacts generated by the run. */
  async #findArtifacts(workingDirectory, startedAt) {
    const resultRoot = path.join(workingDirectory, "results");
    const resultFiles = await findFilesByPredicate(
      resultRoot,
      (_fullPath, fileName) => fileName.endsWith("_static_results.json")
    );
    const reportFiles = await findFilesByPredicate(
      resultRoot,
      (_fullPath, fileName) => fileName.endsWith("_static_summary.md")
    );

    const staticResultsPath = newestSince(resultFiles, startedAt)?.path ?? resultFiles[0]?.path ?? null;
    const markdownReportPath = newestSince(reportFiles, startedAt)?.path ?? reportFiles[0]?.path ?? null;

    return { staticResultsPath, markdownReportPath };
  }
}

/** Selects the newest generated artefact whose modification time matches the current run. */
function newestSince(files, timestampMs) {
  return files.find((file) => file.mtimeMs >= timestampMs - 1000) ?? null;
}

/** Reads an optional Dirty-Waters timeout override from the process environment. */
function readTimeoutFromEnvironment() {
  return parsePositiveInteger(process.env.DIRTY_WATERS_TIMEOUT_MS, DEFAULT_TIMEOUT_MS);
}

/** Parses a positive integer option and falls back when the value is absent or invalid. */
export function parsePositiveInteger(value, fallback) {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed <= 0) {
    return fallback;
  }

  return parsed;
}

/** Builds a concise failure message and highlights common dependency extraction failures. */
function formatDirtyWatersFailure(result, packageManager) {
  const output = `${result.stderr || ""}\n${result.stdout || ""}`.trim();
  const dependencyExtractionHint =
    output.includes("extract_deps_from_npm") || output.includes("WinError 2")
      ? ` Dirty-Waters could not extract ${packageManager} dependencies; verify the required package-manager command is installed and reachable from PATH.`
      : "";

  return `Dirty-Waters failed with exit code ${result.exitCode}.${dependencyExtractionHint}\n${output}`;
}
