import { mkdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { runCommand } from "../../utils/ChildProcess.js";

/** Maps Dirty-Waters package-manager names to the local executable it needs internally. */
const PACKAGE_MANAGER_COMMANDS = Object.freeze({
  npm: "npm",
  pnpm: "pnpm",
  "yarn-classic": "yarn",
  "yarn-berry": "yarn"
});

/** Prepares package-manager commands so Dirty-Waters can invoke them reliably on Windows. */
export class PackageManagerPreflight {
  /** Configures where temporary command shims are written. */
  constructor({ shimRootDirectory = path.join(os.tmpdir(), "dependency-smells-detector-dirty-waters") } = {}) {
    this.shimRootDirectory = shimRootDirectory;
  }

  /** Validates the package manager and returns an env object suitable for Dirty-Waters. */
  async prepareEnvironment({ packageManager, env = process.env, cwd = process.cwd() }) {
    const command = PACKAGE_MANAGER_COMMANDS[packageManager];
    if (!command) {
      throw new Error(`Dirty-Waters package manager '${packageManager}' is not supported by this adapter.`);
    }

    if (process.platform !== "win32") {
      await assertCommandAvailable(command, env, cwd);
      return env;
    }

    const executable = await findWindowsCommand(command, env, cwd);
    if (!executable) {
      throw new Error(
        `Dirty-Waters needs '${command}' on PATH to extract dependencies for package manager '${packageManager}'.`
      );
    }

    const shimDirectory = path.join(this.shimRootDirectory, `run-${process.pid}-${Date.now()}`);
    await mkdir(shimDirectory, { recursive: true });
    await writeWindowsShim(path.join(shimDirectory, `${command}.cmd`), executable);
    await writePythonSubprocessPatch(path.join(shimDirectory, "sitecustomize.py"), {
      [command]: executable
    });

    return {
      ...env,
      PATH: prependPath(env.PATH ?? env.Path ?? "", shimDirectory),
      Path: prependPath(env.Path ?? env.PATH ?? "", shimDirectory),
      PYTHONPATH: prependPath(env.PYTHONPATH ?? "", shimDirectory)
    };
  }
}

/** Verifies that a package manager command can be executed. */
async function assertCommandAvailable(command, env, cwd) {
  const result = await runCommand(command, ["--version"], { cwd, env, timeoutMs: 30 * 1000 });
  if (result.exitCode !== 0) {
    throw new Error(`Package manager command '${command}' failed: ${result.stderr || result.stdout}`);
  }
}

/** Finds the Windows launcher path for npm, yarn, or pnpm. */
async function findWindowsCommand(command, env, cwd) {
  const candidates = [`${command}.cmd`, command];

  for (const candidate of candidates) {
    try {
      const result = await runCommand("where.exe", [candidate], { cwd, env, timeoutMs: 30 * 1000 });
      if (result.exitCode === 0) {
        return selectExecutablePath(result.stdout, command);
      }
    } catch {
      continue;
    }
  }

  return null;
}

/** Selects a command path that Windows can execute directly, preferring .cmd launchers. */
function selectExecutablePath(whereOutput, command) {
  const paths = whereOutput
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  return (
    paths.find((entry) => entry.toLowerCase().endsWith(`${command}.cmd`)) ??
    paths.find((entry) => /\.(exe|cmd|bat)$/i.test(entry)) ??
    paths[0] ??
    null
  );
}

/** Writes a .cmd shim that delegates to the real package-manager launcher. */
async function writeWindowsShim(shimPath, executable) {
  const escapedExecutable = executable.replaceAll("%", "%%");
  await writeFile(shimPath, `@echo off\r\ncall "${escapedExecutable}" %*\r\n`, "utf8");
}

/** Writes a Python startup patch that maps npm/yarn/pnpm to their Windows .cmd launchers. */
async function writePythonSubprocessPatch(patchPath, commandMap) {
  const patch = `# Auto-generated by dependency-smells-detector for Dirty-Waters on Windows.
import subprocess

_COMMAND_MAP = ${JSON.stringify(commandMap, null, 2)}
_ORIGINAL_POPEN = subprocess.Popen

class _PatchedPopen(_ORIGINAL_POPEN):
    def __init__(self, args, *popenargs, **kwargs):
        if isinstance(args, (list, tuple)) and args:
            replacement = _COMMAND_MAP.get(args[0])
            if replacement:
                args = [replacement, *args[1:]]
        elif isinstance(args, str):
            parts = args.split(" ", 1)
            replacement = _COMMAND_MAP.get(parts[0])
            if replacement:
                args = replacement if len(parts) == 1 else replacement + " " + parts[1]
        super().__init__(args, *popenargs, **kwargs)

subprocess.Popen = _PatchedPopen
`;
  await writeFile(patchPath, patch, "utf8");
}

/** Prepends a path entry while preserving the existing platform path separator. */
function prependPath(currentPath, directory) {
  return currentPath ? `${directory}${path.delimiter}${currentPath}` : directory;
}
